openapi: 3.0.4
info:
  title: Pizza API - Subset
  description: API for managing pizza orders and related operations
  version: 1.0.0
servers:
  - url: https://func-pizza-api-vqqlxwmln5lf4.azurewebsites.net/api
    description: Local development server
paths:
  /orders:
    get:
      tags:
        - orders
      summary: Get all orders
      description: Returns a list of all orders in the system
      operationId: getOrders
      parameters:
        - name: userId
          in: query
          description: Filter orders by userId
          explode: false
          schema:
            type: string
        - name: status
          in: query
          description: 'Filter orders by status (comma-separated for multiple, e.g. pending,ready)'
          explode: false
          schema:
            type: string
        - name: last
          in: query
          description: 'Filter orders created in the last X minutes/hours (e.g. 60m, 2h)'
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  required:
                    - id
                    - userId
                    - createdAt
                    - items
                    - estimatedCompletionAt
                    - totalPrice
                    - status
                  type: object
                  properties:
                    id:
                      type: string
                      example: '1618057820123'
                    userId:
                      type: string
                      example: user123
                    createdAt:
                      type: string
                      description: ISO date string of when the order was created
                      format: date-time
                      example: '2025-04-10T14:30:00Z'
                    items:
                      type: array
                      items:
                        required:
                          - pizzaId
                          - quantity
                        type: object
                        properties:
                          pizzaId:
                            type: string
                            example: pizza-1
                          quantity:
                            minimum: 1
                            type: integer
                            example: 1
                          extraToppingIds:
                            type: array
                            items:
                              type: string
                            description: Optional list of extra topping IDs to add to the pizza
                            example:
                              - topping-1
                              - topping-2
                    estimatedCompletionAt:
                      type: string
                      description: ISO date string for estimated completion time
                      format: date-time
                      example: '2025-04-10T15:00:00Z'
                    totalPrice:
                      type: number
                      format: float
                      example: 22.98
                    status:
                      enum:
                        - pending
                        - in-preparation
                        - ready
                        - completed
                        - cancelled
                      type: string
                      description: '- pending: Order has been created but not yet started - in-preparation: Order is being prepared - ready: Order is ready for pickup - completed: Order has been picked up - cancelled: Order has been cancelled'
    post:
      tags:
        - orders
      summary: Create a new order
      description: Places a new order with pizzas (requires userId).
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              required:
                - userId
                - items
              type: object
              properties:
                userId:
                  type: string
                  example: user123
                items:
                  type: array
                  items:
                    required:
                      - pizzaId
                      - quantity
                    type: object
                    properties:
                      pizzaId:
                        type: string
                        example: pizza-1
                      quantity:
                        minimum: 1
                        type: integer
                        example: 1
                      extraToppingIds:
                        type: array
                        items:
                          type: string
                        description: Optional list of extra topping IDs to add to the pizza
                        example:
                          - topping-1
                          - topping-2
        required: true
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                required:
                  - id
                  - userId
                  - createdAt
                  - items
                  - estimatedCompletionAt
                  - totalPrice
                  - status
                type: object
                properties:
                  id:
                    type: string
                    example: '1618057820123'
                  userId:
                    type: string
                    example: user123
                  createdAt:
                    type: string
                    description: ISO date string of when the order was created
                    format: date-time
                    example: '2025-04-10T14:30:00Z'
                  items:
                    type: array
                    items:
                      required:
                        - pizzaId
                        - quantity
                      type: object
                      properties:
                        pizzaId:
                          type: string
                          example: pizza-1
                        quantity:
                          minimum: 1
                          type: integer
                          example: 1
                        extraToppingIds:
                          type: array
                          items:
                            type: string
                          description: Optional list of extra topping IDs to add to the pizza
                          example:
                            - topping-1
                            - topping-2
                  estimatedCompletionAt:
                    type: string
                    description: ISO date string for estimated completion time
                    format: date-time
                    example: '2025-04-10T15:00:00Z'
                  totalPrice:
                    type: number
                    format: float
                    example: 22.98
                  status:
                    enum:
                      - pending
                      - in-preparation
                      - ready
                      - completed
                      - cancelled
                    type: string
                    description: '- pending: Order has been created but not yet started - in-preparation: Order is being prepared - ready: Order is ready for pickup - completed: Order has been picked up - cancelled: Order has been cancelled'
  '/orders/{orderId}':
    get:
      tags:
        - orders
      summary: Get order by ID
      description: Retrieves an order by its ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details found
          content:
            application/json:
              schema:
                required:
                  - id
                  - userId
                  - createdAt
                  - items
                  - estimatedCompletionAt
                  - totalPrice
                  - status
                type: object
                properties:
                  id:
                    type: string
                    example: '1618057820123'
                  userId:
                    type: string
                    example: user123
                  createdAt:
                    type: string
                    description: ISO date string of when the order was created
                    format: date-time
                    example: '2025-04-10T14:30:00Z'
                  items:
                    type: array
                    items:
                      required:
                        - pizzaId
                        - quantity
                      type: object
                      properties:
                        pizzaId:
                          type: string
                          example: pizza-1
                        quantity:
                          minimum: 1
                          type: integer
                          example: 1
                        extraToppingIds:
                          type: array
                          items:
                            type: string
                          description: Optional list of extra topping IDs to add to the pizza
                          example:
                            - topping-1
                            - topping-2
                  estimatedCompletionAt:
                    type: string
                    description: ISO date string for estimated completion time
                    format: date-time
                    example: '2025-04-10T15:00:00Z'
                  totalPrice:
                    type: number
                    format: float
                    example: 22.98
                  status:
                    enum:
                      - pending
                      - in-preparation
                      - ready
                      - completed
                      - cancelled
                    type: string
                    description: '- pending: Order has been created but not yet started - in-preparation: Order is being prepared - ready: Order is ready for pickup - completed: Order has been picked up - cancelled: Order has been cancelled'
    delete:
      tags:
        - orders
      summary: Cancel an order
      description: Cancels an order if it has not yet been started (status must be 'pending')
      operationId: cancelOrder
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                required:
                  - id
                  - userId
                  - createdAt
                  - items
                  - estimatedCompletionAt
                  - totalPrice
                  - status
                type: object
                properties:
                  id:
                    type: string
                    example: '1618057820123'
                  userId:
                    type: string
                    example: user123
                  createdAt:
                    type: string
                    description: ISO date string of when the order was created
                    format: date-time
                    example: '2025-04-10T14:30:00Z'
                  items:
                    type: array
                    items:
                      required:
                        - pizzaId
                        - quantity
                      type: object
                      properties:
                        pizzaId:
                          type: string
                          example: pizza-1
                        quantity:
                          minimum: 1
                          type: integer
                          example: 1
                        extraToppingIds:
                          type: array
                          items:
                            type: string
                          description: Optional list of extra topping IDs to add to the pizza
                          example:
                            - topping-1
                            - topping-2
                  estimatedCompletionAt:
                    type: string
                    description: ISO date string for estimated completion time
                    format: date-time
                    example: '2025-04-10T15:00:00Z'
                  totalPrice:
                    type: number
                    format: float
                    example: 22.98
                  status:
                    enum:
                      - pending
                      - in-preparation
                      - ready
                      - completed
                      - cancelled
                    type: string
                    description: '- pending: Order has been created but not yet started - in-preparation: Order is being prepared - ready: Order is ready for pickup - completed: Order has been picked up - cancelled: Order has been cancelled'
  /pizzas:
    get:
      tags:
        - pizzas
      summary: Get all pizzas
      description: Returns a list of all pizzas
      operationId: getPizzas
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  required:
                    - id
                    - category
                    - name
                    - description
                    - price
                  type: object
                  properties:
                    id:
                      type: string
                      example: pizza-1
                    category:
                      enum:
                        - pizza
                        - drink
                        - side
                        - topping
                      type: string
                    name:
                      type: string
                      example: Margherita Pizza
                    description:
                      type: string
                      example: Classic pizza with tomato sauce and mozzarella
                    price:
                      type: number
                      format: float
                      example: 12.99
  '/pizzas/{id}':
    get:
      tags:
        - pizzas
      summary: Get pizza by ID
      description: Retrieves a specific pizza by its ID
      operationId: getPizzaById
      parameters:
        - name: id
          in: path
          description: ID of the pizza
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pizza details found
          content:
            application/json:
              schema:
                required:
                  - id
                  - category
                  - name
                  - description
                  - price
                type: object
                properties:
                  id:
                    type: string
                    example: pizza-1
                  category:
                    enum:
                      - pizza
                      - drink
                      - side
                      - topping
                    type: string
                  name:
                    type: string
                    example: Margherita Pizza
                  description:
                    type: string
                    example: Classic pizza with tomato sauce and mozzarella
                  price:
                    type: number
                    format: float
                    example: 12.99
  /toppings:
    get:
      tags:
        - toppings
      summary: Get all toppings
      description: Returns a list of all toppings
      operationId: getToppings
      parameters:
        - name: category
          in: query
          description: Filter toppings by category
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: List of toppings
          content:
            application/json:
              schema:
                type: array
                items:
                  required:
                    - id
                    - category
                    - name
                    - description
                    - price
                  type: object
                  properties:
                    id:
                      type: string
                      example: pizza-1
                    category:
                      enum:
                        - pizza
                        - drink
                        - side
                        - topping
                      type: string
                    name:
                      type: string
                      example: Margherita Pizza
                    description:
                      type: string
                      example: Classic pizza with tomato sauce and mozzarella
                    price:
                      type: number
                      format: float
                      example: 12.99
  /toppings/categories:
    get:
      tags:
        - toppings
      summary: Get all topping categories
      description: Returns a list of all topping categories
      operationId: getToppingCategories
      responses:
        '200':
          description: List of topping categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  '/toppings/{id}':
    get:
      tags:
        - toppings
      summary: Get topping by ID
      description: Retrieves a specific topping by its ID
      operationId: getToppingById
      parameters:
        - name: id
          in: path
          description: ID of the topping
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Topping details found
          content:
            application/json:
              schema:
                required:
                  - id
                  - category
                  - name
                  - description
                  - price
                type: object
                properties:
                  id:
                    type: string
                    example: pizza-1
                  category:
                    enum:
                      - pizza
                      - drink
                      - side
                      - topping
                    type: string
                  name:
                    type: string
                    example: Margherita Pizza
                  description:
                    type: string
                    example: Classic pizza with tomato sauce and mozzarella
                  price:
                    type: number
                    format: float
                    example: 12.99
components: { }